{
	"category" : "Voyage-Mongo-Core-Exceptions",
	"classinstvars" : [
		 ],
	"classvars" : [
		 ],
	"commentStamp" : "<historical>",
	"instvars" : [
		"internalErrorsByTimestamp" ],
	"name" : "VOMongoConnectionError",
	"pools" : [
		 ],
	"super" : "VOMongoError",
	"type" : "normal" }
